### PR TITLE
Added keywords

### PR DESCRIPTION
**Pull request by zhibog**
Added keywords from Odin to the snippets according to this document.
[https://github.com/odin-lang/Odin/wiki/Keywords-and-Operators
](url)

### CODE REVIEW

**Comment by zhibog** [comment]
No problem. Could you merge it in?

Also I'm not familar with how the release stuff for VSCode works, but it seems the recent updates have not made it into the extension when you dl it from within VSCode.

**Comment by asmoaesl** [comment]
Yes, sorry I thought I had merged it several hours ago. And yes, I plan to do some work and then publish the latest version of the repo. Essentially, you have to manually send the latest repo to the VSCode extension marketplace as an update. I will do that within the next short while. Thanks again! :)

**Comment by asmoaesl** [comment]
I made [some changes](https://github.com/asmoaesl/odin-vscode/commit/ec20f590494994c95c43d1c08b531cafb7b8f674) and I updated the extension.

**Comment by zhibog** [comment]
Thank you very much. The naming is way better now and moving through via tab makes a ton more sense than having comments.

**Pull request merged**
